package com.foundationdb;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: record_layer_demo.proto

public final class RecordLayerDemoProto {
  private RecordLayerDemoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Color}
   */
  public enum Color
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RED = 1;</code>
     */
    RED(1),
    /**
     * <code>BLUE = 2;</code>
     */
    BLUE(2),
    /**
     * <code>YELLOW = 3;</code>
     */
    YELLOW(3),
    /**
     * <code>PINK = 4;</code>
     */
    PINK(4),
    ;

    /**
     * <code>RED = 1;</code>
     */
    public static final int RED_VALUE = 1;
    /**
     * <code>BLUE = 2;</code>
     */
    public static final int BLUE_VALUE = 2;
    /**
     * <code>YELLOW = 3;</code>
     */
    public static final int YELLOW_VALUE = 3;
    /**
     * <code>PINK = 4;</code>
     */
    public static final int PINK_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Color valueOf(int value) {
      return forNumber(value);
    }

    public static Color forNumber(int value) {
      switch (value) {
        case 1: return RED;
        case 2: return BLUE;
        case 3: return YELLOW;
        case 4: return PINK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Color>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Color> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Color>() {
            public Color findValueByNumber(int number) {
              return Color.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return RecordLayerDemoProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Color[] VALUES = values();

    public static Color valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Color(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Color)
  }

  public interface OrderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Order)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 order_id = 1;</code>
     */
    boolean hasOrderId();
    /**
     * <code>optional int64 order_id = 1;</code>
     */
    long getOrderId();

    /**
     * <code>optional .Flower flower = 2;</code>
     */
    boolean hasFlower();
    /**
     * <code>optional .Flower flower = 2;</code>
     */
    RecordLayerDemoProto.Flower getFlower();
    /**
     * <code>optional .Flower flower = 2;</code>
     */
    RecordLayerDemoProto.FlowerOrBuilder getFlowerOrBuilder();

    /**
     * <code>optional int32 price = 3;</code>
     */
    boolean hasPrice();
    /**
     * <code>optional int32 price = 3;</code>
     */
    int getPrice();
  }
  /**
   * Protobuf type {@code Order}
   */
  public  static final class Order extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Order)
      OrderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Order() {
      orderId_ = 0L;
      price_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Order(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              orderId_ = input.readInt64();
              break;
            }
            case 18: {
              RecordLayerDemoProto.Flower.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = flower_.toBuilder();
              }
              flower_ = input.readMessage(RecordLayerDemoProto.Flower.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(flower_);
                flower_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              price_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RecordLayerDemoProto.internal_static_Order_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RecordLayerDemoProto.internal_static_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RecordLayerDemoProto.Order.class, RecordLayerDemoProto.Order.Builder.class);
    }

    private int bitField0_;
    public static final int ORDER_ID_FIELD_NUMBER = 1;
    private long orderId_;
    /**
     * <code>optional int64 order_id = 1;</code>
     */
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 order_id = 1;</code>
     */
    public long getOrderId() {
      return orderId_;
    }

    public static final int FLOWER_FIELD_NUMBER = 2;
    private RecordLayerDemoProto.Flower flower_;
    /**
     * <code>optional .Flower flower = 2;</code>
     */
    public boolean hasFlower() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Flower flower = 2;</code>
     */
    public RecordLayerDemoProto.Flower getFlower() {
      return flower_ == null ? RecordLayerDemoProto.Flower.getDefaultInstance() : flower_;
    }
    /**
     * <code>optional .Flower flower = 2;</code>
     */
    public RecordLayerDemoProto.FlowerOrBuilder getFlowerOrBuilder() {
      return flower_ == null ? RecordLayerDemoProto.Flower.getDefaultInstance() : flower_;
    }

    public static final int PRICE_FIELD_NUMBER = 3;
    private int price_;
    /**
     * <code>optional int32 price = 3;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 price = 3;</code>
     */
    public int getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, orderId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getFlower());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, price_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, orderId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFlower());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RecordLayerDemoProto.Order)) {
        return super.equals(obj);
      }
      RecordLayerDemoProto.Order other = (RecordLayerDemoProto.Order) obj;

      boolean result = true;
      result = result && (hasOrderId() == other.hasOrderId());
      if (hasOrderId()) {
        result = result && (getOrderId()
            == other.getOrderId());
      }
      result = result && (hasFlower() == other.hasFlower());
      if (hasFlower()) {
        result = result && getFlower()
            .equals(other.getFlower());
      }
      result = result && (hasPrice() == other.hasPrice());
      if (hasPrice()) {
        result = result && (getPrice()
            == other.getPrice());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOrderId()) {
        hash = (37 * hash) + ORDER_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOrderId());
      }
      if (hasFlower()) {
        hash = (37 * hash) + FLOWER_FIELD_NUMBER;
        hash = (53 * hash) + getFlower().hashCode();
      }
      if (hasPrice()) {
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + getPrice();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RecordLayerDemoProto.Order parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecordLayerDemoProto.Order parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecordLayerDemoProto.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecordLayerDemoProto.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecordLayerDemoProto.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecordLayerDemoProto.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecordLayerDemoProto.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RecordLayerDemoProto.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RecordLayerDemoProto.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RecordLayerDemoProto.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RecordLayerDemoProto.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RecordLayerDemoProto.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RecordLayerDemoProto.Order prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Order}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Order)
        RecordLayerDemoProto.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RecordLayerDemoProto.internal_static_Order_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RecordLayerDemoProto.internal_static_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RecordLayerDemoProto.Order.class, RecordLayerDemoProto.Order.Builder.class);
      }

      // Construct using RecordLayerDemoProto.Order.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFlowerFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        orderId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (flowerBuilder_ == null) {
          flower_ = null;
        } else {
          flowerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RecordLayerDemoProto.internal_static_Order_descriptor;
      }

      @Override
      public RecordLayerDemoProto.Order getDefaultInstanceForType() {
        return RecordLayerDemoProto.Order.getDefaultInstance();
      }

      @Override
      public RecordLayerDemoProto.Order build() {
        RecordLayerDemoProto.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RecordLayerDemoProto.Order buildPartial() {
        RecordLayerDemoProto.Order result = new RecordLayerDemoProto.Order(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.orderId_ = orderId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (flowerBuilder_ == null) {
          result.flower_ = flower_;
        } else {
          result.flower_ = flowerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.price_ = price_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RecordLayerDemoProto.Order) {
          return mergeFrom((RecordLayerDemoProto.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RecordLayerDemoProto.Order other) {
        if (other == RecordLayerDemoProto.Order.getDefaultInstance()) return this;
        if (other.hasOrderId()) {
          setOrderId(other.getOrderId());
        }
        if (other.hasFlower()) {
          mergeFlower(other.getFlower());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RecordLayerDemoProto.Order parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RecordLayerDemoProto.Order) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long orderId_ ;
      /**
       * <code>optional int64 order_id = 1;</code>
       */
      public boolean hasOrderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 order_id = 1;</code>
       */
      public long getOrderId() {
        return orderId_;
      }
      /**
       * <code>optional int64 order_id = 1;</code>
       */
      public Builder setOrderId(long value) {
        bitField0_ |= 0x00000001;
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 order_id = 1;</code>
       */
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        orderId_ = 0L;
        onChanged();
        return this;
      }

      private RecordLayerDemoProto.Flower flower_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Flower, Flower.Builder, FlowerOrBuilder> flowerBuilder_;
      /**
       * <code>optional .Flower flower = 2;</code>
       */
      public boolean hasFlower() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Flower flower = 2;</code>
       */
      public RecordLayerDemoProto.Flower getFlower() {
        if (flowerBuilder_ == null) {
          return flower_ == null ? RecordLayerDemoProto.Flower.getDefaultInstance() : flower_;
        } else {
          return flowerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Flower flower = 2;</code>
       */
      public Builder setFlower(RecordLayerDemoProto.Flower value) {
        if (flowerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          flower_ = value;
          onChanged();
        } else {
          flowerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Flower flower = 2;</code>
       */
      public Builder setFlower(
          RecordLayerDemoProto.Flower.Builder builderForValue) {
        if (flowerBuilder_ == null) {
          flower_ = builderForValue.build();
          onChanged();
        } else {
          flowerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Flower flower = 2;</code>
       */
      public Builder mergeFlower(RecordLayerDemoProto.Flower value) {
        if (flowerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              flower_ != null &&
              flower_ != RecordLayerDemoProto.Flower.getDefaultInstance()) {
            flower_ =
              RecordLayerDemoProto.Flower.newBuilder(flower_).mergeFrom(value).buildPartial();
          } else {
            flower_ = value;
          }
          onChanged();
        } else {
          flowerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Flower flower = 2;</code>
       */
      public Builder clearFlower() {
        if (flowerBuilder_ == null) {
          flower_ = null;
          onChanged();
        } else {
          flowerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Flower flower = 2;</code>
       */
      public RecordLayerDemoProto.Flower.Builder getFlowerBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getFlowerFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Flower flower = 2;</code>
       */
      public RecordLayerDemoProto.FlowerOrBuilder getFlowerOrBuilder() {
        if (flowerBuilder_ != null) {
          return flowerBuilder_.getMessageOrBuilder();
        } else {
          return flower_ == null ?
              RecordLayerDemoProto.Flower.getDefaultInstance() : flower_;
        }
      }
      /**
       * <code>optional .Flower flower = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Flower, Flower.Builder, FlowerOrBuilder>
          getFlowerFieldBuilder() {
        if (flowerBuilder_ == null) {
          flowerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Flower, Flower.Builder, FlowerOrBuilder>(
                  getFlower(),
                  getParentForChildren(),
                  isClean());
          flower_ = null;
        }
        return flowerBuilder_;
      }

      private int price_ ;
      /**
       * <code>optional int32 price = 3;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 price = 3;</code>
       */
      public int getPrice() {
        return price_;
      }
      /**
       * <code>optional int32 price = 3;</code>
       */
      public Builder setPrice(int value) {
        bitField0_ |= 0x00000004;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 price = 3;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Order)
    }

    // @@protoc_insertion_point(class_scope:Order)
    private static final RecordLayerDemoProto.Order DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RecordLayerDemoProto.Order();
    }

    public static RecordLayerDemoProto.Order getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Order>
        PARSER = new com.google.protobuf.AbstractParser<Order>() {
      @Override
      public Order parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Order(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Order> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    @Override
    public RecordLayerDemoProto.Order getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FlowerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Flower)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional string type = 1;</code>
     */
    String getType();
    /**
     * <code>optional string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional .Color color = 2;</code>
     */
    boolean hasColor();
    /**
     * <code>optional .Color color = 2;</code>
     */
    RecordLayerDemoProto.Color getColor();
  }
  /**
   * Protobuf type {@code Flower}
   */
  public  static final class Flower extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Flower)
      FlowerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Flower.newBuilder() to construct.
    private Flower(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Flower() {
      type_ = "";
      color_ = 1;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Flower(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              type_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              RecordLayerDemoProto.Color value = RecordLayerDemoProto.Color.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                color_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RecordLayerDemoProto.internal_static_Flower_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RecordLayerDemoProto.internal_static_Flower_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RecordLayerDemoProto.Flower.class, RecordLayerDemoProto.Flower.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile Object type_;
    /**
     * <code>optional string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLOR_FIELD_NUMBER = 2;
    private int color_;
    /**
     * <code>optional .Color color = 2;</code>
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Color color = 2;</code>
     */
    public RecordLayerDemoProto.Color getColor() {
      @SuppressWarnings("deprecation")
      RecordLayerDemoProto.Color result = RecordLayerDemoProto.Color.valueOf(color_);
      return result == null ? RecordLayerDemoProto.Color.RED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, color_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, color_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RecordLayerDemoProto.Flower)) {
        return super.equals(obj);
      }
      RecordLayerDemoProto.Flower other = (RecordLayerDemoProto.Flower) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && getType()
            .equals(other.getType());
      }
      result = result && (hasColor() == other.hasColor());
      if (hasColor()) {
        result = result && color_ == other.color_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasColor()) {
        hash = (37 * hash) + COLOR_FIELD_NUMBER;
        hash = (53 * hash) + color_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RecordLayerDemoProto.Flower parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecordLayerDemoProto.Flower parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecordLayerDemoProto.Flower parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecordLayerDemoProto.Flower parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecordLayerDemoProto.Flower parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecordLayerDemoProto.Flower parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecordLayerDemoProto.Flower parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RecordLayerDemoProto.Flower parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RecordLayerDemoProto.Flower parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RecordLayerDemoProto.Flower parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RecordLayerDemoProto.Flower parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RecordLayerDemoProto.Flower parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RecordLayerDemoProto.Flower prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Flower}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Flower)
        RecordLayerDemoProto.FlowerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RecordLayerDemoProto.internal_static_Flower_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RecordLayerDemoProto.internal_static_Flower_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RecordLayerDemoProto.Flower.class, RecordLayerDemoProto.Flower.Builder.class);
      }

      // Construct using RecordLayerDemoProto.Flower.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        color_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RecordLayerDemoProto.internal_static_Flower_descriptor;
      }

      @Override
      public RecordLayerDemoProto.Flower getDefaultInstanceForType() {
        return RecordLayerDemoProto.Flower.getDefaultInstance();
      }

      @Override
      public RecordLayerDemoProto.Flower build() {
        RecordLayerDemoProto.Flower result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RecordLayerDemoProto.Flower buildPartial() {
        RecordLayerDemoProto.Flower result = new RecordLayerDemoProto.Flower(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.color_ = color_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RecordLayerDemoProto.Flower) {
          return mergeFrom((RecordLayerDemoProto.Flower)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RecordLayerDemoProto.Flower other) {
        if (other == RecordLayerDemoProto.Flower.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasColor()) {
          setColor(other.getColor());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RecordLayerDemoProto.Flower parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RecordLayerDemoProto.Flower) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object type_ = "";
      /**
       * <code>optional string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string type = 1;</code>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 1;</code>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      private int color_ = 1;
      /**
       * <code>optional .Color color = 2;</code>
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Color color = 2;</code>
       */
      public RecordLayerDemoProto.Color getColor() {
        @SuppressWarnings("deprecation")
        RecordLayerDemoProto.Color result = RecordLayerDemoProto.Color.valueOf(color_);
        return result == null ? RecordLayerDemoProto.Color.RED : result;
      }
      /**
       * <code>optional .Color color = 2;</code>
       */
      public Builder setColor(RecordLayerDemoProto.Color value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        color_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .Color color = 2;</code>
       */
      public Builder clearColor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        color_ = 1;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Flower)
    }

    // @@protoc_insertion_point(class_scope:Flower)
    private static final RecordLayerDemoProto.Flower DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RecordLayerDemoProto.Flower();
    }

    public static RecordLayerDemoProto.Flower getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Flower>
        PARSER = new com.google.protobuf.AbstractParser<Flower>() {
      @Override
      public Flower parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Flower(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Flower> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Flower> getParserForType() {
      return PARSER;
    }

    @Override
    public RecordLayerDemoProto.Flower getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UnionDescriptorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UnionDescriptor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Order _Order = 1;</code>
     */
    boolean hasOrder();
    /**
     * <code>optional .Order _Order = 1;</code>
     */
    RecordLayerDemoProto.Order getOrder();
    /**
     * <code>optional .Order _Order = 1;</code>
     */
    RecordLayerDemoProto.OrderOrBuilder getOrderOrBuilder();
  }
  /**
   * Protobuf type {@code UnionDescriptor}
   */
  public  static final class UnionDescriptor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UnionDescriptor)
      UnionDescriptorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UnionDescriptor.newBuilder() to construct.
    private UnionDescriptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UnionDescriptor() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UnionDescriptor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              RecordLayerDemoProto.Order.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = Order_.toBuilder();
              }
              Order_ = input.readMessage(RecordLayerDemoProto.Order.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(Order_);
                Order_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RecordLayerDemoProto.internal_static_UnionDescriptor_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RecordLayerDemoProto.internal_static_UnionDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RecordLayerDemoProto.UnionDescriptor.class, RecordLayerDemoProto.UnionDescriptor.Builder.class);
    }

    private int bitField0_;
    public static final int _ORDER_FIELD_NUMBER = 1;
    private RecordLayerDemoProto.Order Order_;
    /**
     * <code>optional .Order _Order = 1;</code>
     */
    public boolean hasOrder() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Order _Order = 1;</code>
     */
    public RecordLayerDemoProto.Order getOrder() {
      return Order_ == null ? RecordLayerDemoProto.Order.getDefaultInstance() : Order_;
    }
    /**
     * <code>optional .Order _Order = 1;</code>
     */
    public RecordLayerDemoProto.OrderOrBuilder getOrderOrBuilder() {
      return Order_ == null ? RecordLayerDemoProto.Order.getDefaultInstance() : Order_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getOrder());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getOrder());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RecordLayerDemoProto.UnionDescriptor)) {
        return super.equals(obj);
      }
      RecordLayerDemoProto.UnionDescriptor other = (RecordLayerDemoProto.UnionDescriptor) obj;

      boolean result = true;
      result = result && (hasOrder() == other.hasOrder());
      if (hasOrder()) {
        result = result && getOrder()
            .equals(other.getOrder());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOrder()) {
        hash = (37 * hash) + _ORDER_FIELD_NUMBER;
        hash = (53 * hash) + getOrder().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RecordLayerDemoProto.UnionDescriptor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecordLayerDemoProto.UnionDescriptor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecordLayerDemoProto.UnionDescriptor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecordLayerDemoProto.UnionDescriptor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecordLayerDemoProto.UnionDescriptor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecordLayerDemoProto.UnionDescriptor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecordLayerDemoProto.UnionDescriptor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RecordLayerDemoProto.UnionDescriptor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RecordLayerDemoProto.UnionDescriptor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RecordLayerDemoProto.UnionDescriptor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RecordLayerDemoProto.UnionDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RecordLayerDemoProto.UnionDescriptor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RecordLayerDemoProto.UnionDescriptor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UnionDescriptor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UnionDescriptor)
        RecordLayerDemoProto.UnionDescriptorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RecordLayerDemoProto.internal_static_UnionDescriptor_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RecordLayerDemoProto.internal_static_UnionDescriptor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RecordLayerDemoProto.UnionDescriptor.class, RecordLayerDemoProto.UnionDescriptor.Builder.class);
      }

      // Construct using RecordLayerDemoProto.UnionDescriptor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOrderFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (OrderBuilder_ == null) {
          Order_ = null;
        } else {
          OrderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RecordLayerDemoProto.internal_static_UnionDescriptor_descriptor;
      }

      @Override
      public RecordLayerDemoProto.UnionDescriptor getDefaultInstanceForType() {
        return RecordLayerDemoProto.UnionDescriptor.getDefaultInstance();
      }

      @Override
      public RecordLayerDemoProto.UnionDescriptor build() {
        RecordLayerDemoProto.UnionDescriptor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RecordLayerDemoProto.UnionDescriptor buildPartial() {
        RecordLayerDemoProto.UnionDescriptor result = new RecordLayerDemoProto.UnionDescriptor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (OrderBuilder_ == null) {
          result.Order_ = Order_;
        } else {
          result.Order_ = OrderBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RecordLayerDemoProto.UnionDescriptor) {
          return mergeFrom((RecordLayerDemoProto.UnionDescriptor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RecordLayerDemoProto.UnionDescriptor other) {
        if (other == RecordLayerDemoProto.UnionDescriptor.getDefaultInstance()) return this;
        if (other.hasOrder()) {
          mergeOrder(other.getOrder());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RecordLayerDemoProto.UnionDescriptor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RecordLayerDemoProto.UnionDescriptor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private RecordLayerDemoProto.Order Order_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Order, Order.Builder, OrderOrBuilder> OrderBuilder_;
      /**
       * <code>optional .Order _Order = 1;</code>
       */
      public boolean hasOrder() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Order _Order = 1;</code>
       */
      public RecordLayerDemoProto.Order getOrder() {
        if (OrderBuilder_ == null) {
          return Order_ == null ? RecordLayerDemoProto.Order.getDefaultInstance() : Order_;
        } else {
          return OrderBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Order _Order = 1;</code>
       */
      public Builder setOrder(RecordLayerDemoProto.Order value) {
        if (OrderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          Order_ = value;
          onChanged();
        } else {
          OrderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Order _Order = 1;</code>
       */
      public Builder setOrder(
          RecordLayerDemoProto.Order.Builder builderForValue) {
        if (OrderBuilder_ == null) {
          Order_ = builderForValue.build();
          onChanged();
        } else {
          OrderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Order _Order = 1;</code>
       */
      public Builder mergeOrder(RecordLayerDemoProto.Order value) {
        if (OrderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              Order_ != null &&
              Order_ != RecordLayerDemoProto.Order.getDefaultInstance()) {
            Order_ =
              RecordLayerDemoProto.Order.newBuilder(Order_).mergeFrom(value).buildPartial();
          } else {
            Order_ = value;
          }
          onChanged();
        } else {
          OrderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Order _Order = 1;</code>
       */
      public Builder clearOrder() {
        if (OrderBuilder_ == null) {
          Order_ = null;
          onChanged();
        } else {
          OrderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Order _Order = 1;</code>
       */
      public RecordLayerDemoProto.Order.Builder getOrderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getOrderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Order _Order = 1;</code>
       */
      public RecordLayerDemoProto.OrderOrBuilder getOrderOrBuilder() {
        if (OrderBuilder_ != null) {
          return OrderBuilder_.getMessageOrBuilder();
        } else {
          return Order_ == null ?
              RecordLayerDemoProto.Order.getDefaultInstance() : Order_;
        }
      }
      /**
       * <code>optional .Order _Order = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Order, Order.Builder, OrderOrBuilder>
          getOrderFieldBuilder() {
        if (OrderBuilder_ == null) {
          OrderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Order, Order.Builder, OrderOrBuilder>(
                  getOrder(),
                  getParentForChildren(),
                  isClean());
          Order_ = null;
        }
        return OrderBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UnionDescriptor)
    }

    // @@protoc_insertion_point(class_scope:UnionDescriptor)
    private static final RecordLayerDemoProto.UnionDescriptor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RecordLayerDemoProto.UnionDescriptor();
    }

    public static RecordLayerDemoProto.UnionDescriptor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<UnionDescriptor>
        PARSER = new com.google.protobuf.AbstractParser<UnionDescriptor>() {
      @Override
      public UnionDescriptor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UnionDescriptor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UnionDescriptor> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UnionDescriptor> getParserForType() {
      return PARSER;
    }

    @Override
    public RecordLayerDemoProto.UnionDescriptor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Order_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Order_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Flower_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Flower_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UnionDescriptor_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UnionDescriptor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027record_layer_demo.proto\032\035record_metada" +
      "ta_options.proto\"A\n\005Order\022\020\n\010order_id\030\001 " +
      "\001(\003\022\027\n\006flower\030\002 \001(\0132\007.Flower\022\r\n\005price\030\003 " +
      "\001(\005\"-\n\006Flower\022\014\n\004type\030\001 \001(\t\022\025\n\005color\030\002 \001" +
      "(\0162\006.Color\"0\n\017UnionDescriptor\022\026\n\006_Order\030" +
      "\001 \001(\0132\006.Order:\005\212M\002\010\002*0\n\005Color\022\007\n\003RED\020\001\022\010" +
      "\n\004BLUE\020\002\022\n\n\006YELLOW\020\003\022\010\n\004PINK\020\004B\026B\024Record" +
      "LayerDemoProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.apple.foundationdb.record.RecordMetaDataOptionsProto.getDescriptor(),
        }, assigner);
    internal_static_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Order_descriptor,
        new String[] { "OrderId", "Flower", "Price", });
    internal_static_Flower_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Flower_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Flower_descriptor,
        new String[] { "Type", "Color", });
    internal_static_UnionDescriptor_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UnionDescriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UnionDescriptor_descriptor,
        new String[] { "Order", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.apple.foundationdb.record.RecordMetaDataOptionsProto.record);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.apple.foundationdb.record.RecordMetaDataOptionsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
